# -*- coding: utf-8 -*-
"""reglas.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1M0kVoGE5KvJ62g__rPa3JMi-QqNEtHqx

#Market Basket

###Importación de librerias
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

"""###Asignacion de la ubicacion de los datos"""

dire = "Order_products.csv"
dire2="Order_products.csv"

"""###Carga de datos """

dataset=pd.read_csv(dire,encoding='utf-8',engine='python',quoting=3)
data=pd.read_csv(dire2,encoding='utf-8',engine='python',quoting=3)

data

"""###Reacomodamos los datos para poder utilizarlos en el algoritmo """

dataset=dataset.pivot(index="order_id",columns="add_to_cart_order",values="product_name")

dataset

"""###Observamos con que frecuencia absoluta aparecen en las transacciones los productos productos """

productos=data['product_name'].value_counts()
boxplot=data['product_name'].value_counts()
productos=pd.DataFrame(productos)
productos

"""###Estadistica descriptiva de los productos"""

print((productos/1384616).describe())

"""###Grafica de frecuencia relativa de los primeros 50 productos """

plt.stem(productos.index[0:20],((np.array(productos)/1384616)[0:20]))
plt.xticks(rotation=90)
plt.show()

"""### Boxplot de la frecuencia relativa """

#para definir el soporte se hizo el siguiente analisis
plt.boxplot(boxplot/1384616,showfliers=False) 
plt.show()

"""### Algortimo reglas de asociación """

transactions =[]
for i in range(0,131209):
    transactions.append([str(dataset.values[i,j]) for j in range(1,80)])
from apyori import apriori
rules=apriori(transactions,min_support=0.0009,min_confidence=.1,min_lift =5 ,min_length=2)
results=list(rules)
from apyori import inspect 
frame = pd.DataFrame(inspect(results),columns=['recomendaciones','compra','soporte','confianza','lift'])

"""#Resultados"""

frame